### ISSUE TITLE
Retrieving saved subclass results in detached entity in Micronaut Project with Neo4j

### ISSUE THREAD

**Issue by jisikoff** [micronaut-projects/micronaut-neo4j#1]
I have a class hierarchy that was behaving badly and finally noticed that lots of retrieved subclasses were coming back as not attached from finders causing them to try to be persisted again when transaction flushes.  I've tried to reduce it to the simplest example:
This is in Micronaut 1.1.0.M2 and neo4j 3.5.0 (though I also tried the latest) and java driver 1.7.2
Be aware the test leaves junk in neo and must be cleaned out manually between runs this was the only way I could reproduce...
```groovy 
@MicronautTest
class SubclassAttachedSpec extends Specification {

    @Transactional
    void "Test saving subclass and leaving it for next test"() {
        given: "a subclass "
                new Sub(name: "sub").save(flush: true) //if I create this as new Base both tests work
                Base retrieved = Base.findByName("sub")

        expect:
                retrieved.isAttached()
    }

    @Transactional
    void "retrieve again"() {
        given: "existing subclass"
                Base found = Base.findByName("sub")

        expect: "it to be attached"
                found.isAttached()  //for Sub, this fails as unattached but entity looks loaded in debugger
    }
}

@CompileStatic
@Entity
class Base implements Neo4jEntity<Base> {
    String name
}

@CompileStatic
@Entity
class Sub extends Base implements Neo4jEntity<Sub> {
}
```

**Comment by ilopmar** [comment]
@jisikoff Can you please test with Micronaut 2.0?
Also it would be great if you can share a simple application that reproduces the issue with the different steps about how to reproduce it.

**Comment by ilopmar** [comment]
Closing due to the lack of feedback. If the problem persists please open a new issue with an test application that reproduces it.
