### ISSUE TITLE
Missing artifacts for Micronaut Neo4j 4.0.0

### ISSUE THREAD

**Issue by michael-simons** [micronaut-projects/micronaut-neo4j#75]
Hello everyone.

I went to https://micronaut.io/launch/ for generating a project. To my pleasant surprise I find that I can have Neo4j bolt pure.
However, both Gradle and Maven parents point to `io.micronaut.neo4j:micronaut-neo4j-bolt:4.0.0` which is neither on Central nor on Bintray. Please change either https://github.com/micronaut-projects/micronaut-core/blob/2.1.x/gradle.properties to point to the released version 3.0.2 or release the 4.0.0 to central.

Thanks a lot.

**Comment by michael-simons** [comment]
Ok, the latest piece being on central is 3.0.0. This should definitely be fixed for a more pleasant getting started experience with Neo4j. Thank you!

**Comment by graemerocher** [comment]
@alvarosanchez do you know what happened to the 4.0.0 release? https://github.com/micronaut-projects/micronaut-neo4j/runs/1096195198?check_suite_focus=true

Seems it completed successfully but no artifacts were published? Were they deleted?

**Comment by alvarosanchez** [comment]
@graemerocher no idea, sorry. I guess this needs to be published manually from the tag.

@sdelamo did the release. Sergio, do you recall if they were published on Bintray? Maybe we can contact JFrog support.

**Comment by ilopmar** [comment]
The action to release to Central for 4.0.0 wasn't run: https://github.com/micronaut-projects/micronaut-neo4j/actions?query=workflow%3A%22Maven+Central+Sync%22

**Comment by graemerocher** [comment]
@sdelamo do you recall what happened?

**Comment by graemerocher** [comment]
@alvarosanchez also isn't our BOM validation supposed to catch problems like this?

**Comment by alvarosanchez** [comment]
> @alvarosanchez also isn't our BOM validation supposed to catch problems like this?

It seems it isn't working as expected, or at least not for this case.

**Comment by alvarosanchez** [comment]
This is why it didn't catch it: https://github.com/micronaut-projects/micronaut-core/pull/4473

**Comment by sdelamo** [comment]
I don't remember what happened. based on this: 

> The action to release to Central for 4.0.0 wasn't run: https://github.com/micronaut-projects/micronaut-neo4j/actions?query=workflow%3A%22Maven+Central+Sync%22

I probably forgot to run the sync.

Should I run it for 4.0.0 ?
